### ISSUE TITLE
原文链接404了

### ISSUE THREAD

**Issue by heisen-li** [Milittle/effective-rust-cn#1]
![image](https://github.com/Milittle/effective-rust-cn/assets/46313511/0ea5f5df-370a-450b-94ef-f4a999a98e94)

**Comment by Milittle** [comment]
> ![image](https://private-user-images.githubusercontent.com/46313511/329116681-0ea5f5df-370a-450b-94ef-f4a999a98e94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTQ0NzEsIm5iZiI6MTcxNTM1NDE3MSwicGF0aCI6Ii80NjMxMzUxMS8zMjkxMTY2ODEtMGVhNWY1ZGYtMzcwYS00NTBiLTk0ZWYtZjRhOTk5YTk4ZTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE1MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjc0OTgyZmQzODU2MjliZGZiNWQ4MzUzMjdiZjY4Njc1MTI0ZTZmYzg1MWI1Y2E2NjgxOTJjMmZlNzY3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OlXwB1CmyhfKRz0y8ZWJPAQkjGipVf_MV-RGZ4OlL9g)

Fixed:

https://github.com/Milittle/effective-rust-cn/commit/15303aaf181fb3e0ed8f8573a925d22586e2aa3d
